name: data packages validation

on:
  push:
    branches:
      - issue-150
      # - main
    paths:
      # - 'data/**'
  pull_request:
    branches:
      - main
    paths:
      - 'data/**'

jobs:
  frictionless-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate data
        uses: frictionlessdata/repository@v2
